=== DatDonathan/pokemine/res/ressources/xml/trainer/trainer_rank.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:trrk="https://jojokobi.lima-city.de/pokemine/trainer"
	targetNamespace="https://jojokobi.lima-city.de/pokemine/trainer"
	elementFormDefault="qualified" xmlns:Q1="https://jojokobi.lima-city.de/pokemine/pokemon_species">
	
    <import schemaLocation="../pokemon/pokemon_species.xsd" namespace="https://jojokobi.lima-city.de/pokemine/pokemon_species"></import>
    <complexType name="trainer_rank">
    	<sequence>
    		<element name="name" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="identifier" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="id" type="int" minOccurs="1" maxOccurs="1"></element>
    		<element name="spawnable" type="boolean" minOccurs="1"
    			maxOccurs="1">
    		</element>
            <element name="prize" type="int" minOccurs="1" maxOccurs="1"></element>
            <element name="types" type="Q1:types" minOccurs="1"
    			maxOccurs="1">
    		</element>

    		<element name="names" type="trrk:names" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="used_pokemon" type="trrk:used_pokemon"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="start_texts" type="trrk:texts" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="win_texts" type="trrk:texts" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="lose_texts" type="trrk:texts" minOccurs="1"
    			maxOccurs="1">
    		</element>

    		<element name="badge" type="Q1:type" minOccurs="0"
    			maxOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <element name="trainer_rank" type="trrk:trainer_rank"></element>

    <complexType name="names">
    	<sequence>
    		<element name="name" type="string" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="texts">
    	<sequence>
    		<element name="text" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="used_pokemon">
    	<sequence>
    		<element name="pokemon" type="string" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
</schema>

=== DatDonathan/pokemine/res/ressources/xml/trainer/developer.xml
<?xml version="1.0" encoding="UTF-8"?>
<trainer_rank xmlns="https://jojokobi.lima-city.de/pokemine/trainer_rank" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="https://jojokobi.lima-city.de/pokemine/trainer_rank trainer_rank.xsd">
	<name>Developer</name>
	<identifier>developer</identifier>
	<id>1</id>
	<spawnable>false</spawnable>
	<prize>80</prize>
	<types>
	</types>
	<names>
		<name>jojokobi</name>
	</names>
	<used_pokemon>
		<pokemon>blastoise</pokemon>
		<pokemon>snorlax</pokemon>
		<pokemon>jolteon</pokemon>
		<pokemon>aerodactyl</pokemon>
		<pokemon>wobbuffet</pokemon>
		<pokemon>golem</pokemon>
		<pokemon>gengar</pokemon>
	</used_pokemon>
	<start_texts>
		<text>I choose you!</text>
		<text>Well then! Let's battle!</text>
		<text>We're going to make it! Let's gooooo!</text>
	</start_texts>
	<win_texts>
		<text>That's what i expected!</text>
		<text>You did a good job!</text>
		<text>Yeah, I won!</text>
	</win_texts>
	<lose_texts>
		<text>Ok, let's go to the Pokécenter!</text>
		<text>I think I need to nerf you pkokémon!</text>
	</lose_texts>
</trainer_rank>
